project 'MeiLa.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MeiLa' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MeiLa
pod 'AFNetworking'
pod 'YYModel'
pod 'SDWebImage'
pod 'SVPullToRefresh'
pod 'Masonry'
pod 'UITableView+FDTemplateLayoutCell'
pod 'ZYBannerView'
end
